before_install:
  - pod repo update > /dev/null
script:
 - xcodebuild -workspace Cosmic.xcworkspace -scheme Cosmic build test

language: objective-c
osx_image: xcode8.3
xcode_workspace: Cosmic.xcworkspace # path to your xcodeproj folder
xcode_scheme: Cosmic
